language: c
compiler:
  - clang
  - gcc

matrix:
    fast_finish: true
    allow_failures:
        - compiler: clang

install: sudo apt-get install cmake libgtk-3-dev librsvg2-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
