language: c
compiler:
  - clang
  - gcc
os:
  - linux
  - osx

before_script:
  - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.bz2
  - bunzip2 -c jansson-2.7.tar.bz2 | tar xf -
  - cd jansson-2.7
  - ./configure --prefix=$HOME
  - make
  - make install
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - cd -
  - export LD_LIBRARY_PATH=LD_LIBRARY_PATH:$HOME/lib/

script:
  - make
  - ./sailsd
