version: "{branch}-ci-{build}"
clone_depth: 5

environment:
  matrix:
    - GENERATOR: MinGW Makefiles

configuration: Debug

before_build:
  - rm "C:/Program Files/Git/usr/bin/sh.exe"
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..

build_script:
  - cmake --build . --config %CONFIGURATION%
